SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_DATABASE_URI = 'sqlite:///./data.db'
SECRET_KEY = b'gv\xe3\xe2V\x87\x1b\xe4\xc9>1\x89\xcen\x1b3'
POSTS_PER_PAGE = 8
REPLIES_PER_PAGE = 5


MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = '587'
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = "343476409@qq.com"
MAIL_PASSWORD = "hrqtutzhlkducaji"

